.test-commands: &test-commands
  script:
    - tox -e setup,flake8
  before_script:
    - python -V
    - pip install tox
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

test:python27:
  <<: *test-commands
  image: python:2.7

test:python34:
  <<: *test-commands
  image: python:3.4

test:python35:
  <<: *test-commands
  image: python:3.5

test:python36:
  <<: *test-commands
  image: python:3.6
